apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  namespace: jitsi
data:
    JICOFO_COMPONENT_SECRET: "O2BgMqjau3Rb"
    JICOFO_AUTH_PASSWORD: "O2BgMqjau3Rb"
    JVB_AUTH_PASSWORD: "O2BgMqjau3Rb"
