apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    k8s-app: jitsi
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: jitsi
   namespace: jitsi
 spec:
  tls:
    - hosts:
      - linuxawy.co
      secretName: tls-secret
  rules:
  - host: linuxawy.co
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
